import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { makeDir, makeHome } from "../test-support/memory.mjs";

const CLI = fileURLToPath(new URL("../bin/nightshift.mjs", import.meta.url));

const NPM_V3 = `${JSON.stringify(
  {
    name: "fixture",
    lockfileVersion: 3,
    packages: {
      "": { name: "fixture", dependencies: { zod: "^4.5.4", "@scope/sdk": "^1.30.0" } },
      "node_modules/@scope/sdk": { version: "1.30.0", resolved: "https://registry.npmjs.org/@scope/sdk/-/sdk-1.30.0.tgz" },
      "node_modules/zod": { version: "4.5.4", resolved: "https://registry.npmjs.org/zod/-/zod-4.5.4.tgz" },
      "node_modules/eslint/node_modules/zod": { version: "9.9.9" },
    },
  },
  null,
  2,
)}\n`;

const NPM_V1 = `${JSON.stringify(
  {
    name: "fixture",
    lockfileVersion: 1,
    dependencies: {
      zod: { version: "3.22.4", requires: { "left-pad": "^1.0.0" } },
      "@scope/sdk": { version: "0.9.1", dependencies: { "left-pad": { version: "1.3.0" } } },
    },
  },
  null,
  2,
)}\n`;

const PNPM = `lockfileVersion: '9.0'

importers:

  .:
    dependencies:
      zod:
        specifier: ^4.5.4
        version: 4.5.4

packages:

  '@scope/sdk@1.30.0':
    resolution: {integrity: sha512-aaa}

  zod@4.5.4:
    resolution: {integrity: sha512-bbb}

  zod-to-json-schema@3.24.1:
    resolution: {integrity: sha512-ccc}
    peerDependencies:
      zod: ^3.24.1

snapshots:

  zod@4.5.4: {}

  zod-to-json-schema@3.24.1(zod@4.5.4): {}
`;

const YARN_CLASSIC = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@scope/sdk@^1.30.0":
  version "1.30.0"
  resolved "https://registry.yarnpkg.com/@scope/sdk/-/sdk-1.30.0.tgz#aaa"
  integrity sha512-aaa

zod@^3.22.0, zod@^3.22.4:
  version "3.22.4"
  resolved "https://registry.yarnpkg.com/zod/-/zod-3.22.4.tgz#bbb"
  integrity sha512-bbb
`;

const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8

"@scope/sdk@npm:^1.30.0":
  version: 1.30.0
  resolution: "@scope/sdk@npm:1.30.0"
  checksum: aaa
  languageName: node
  linkType: hard

"zod@npm:^4.5.4, zod@npm:4.5.4":
  version: 4.5.4
  resolution: "zod@npm:4.5.4"
  checksum: bbb
  languageName: node
  linkType: hard
`;

const POETRY = `[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"

[[package]]
name = "urllib3"
version = "2.2.1"
description = "HTTP library with thread-safe connection pooling."
optional = false
`;

const REQUIREMENTS = `# application dependencies
requests==2.31.0
urllib3 == 2.2.1 ; python_version >= "3.8"
`;

const CARGO = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.197"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.197"
`;

const GO_SUM = `github.com/google/uuid v1.6.0 h1:aaa=
github.com/google/uuid v1.6.0/go.mod h1:bbb=
golang.org/x/sys v0.18.0/go.mod h1:ccc=
`;

const GO_MOD = `module example.com/app

go 1.22

require (
	github.com/google/uuid v1.6.0
	golang.org/x/sys v0.18.0
)
`;

const FIXTURES = [
  { format: "package-lock.json v3", file: "package-lock.json", content: NPM_V3, names: ["zod", "@scope/sdk"], expected: ["zod 4.5.4", "@scope/sdk 1.30.0"] },
  { format: "package-lock.json v1", file: "package-lock.json", content: NPM_V1, names: ["zod", "@scope/sdk", "left-pad"], expected: ["zod 3.22.4", "@scope/sdk 0.9.1", "left-pad 1.3.0"] },
  { format: "pnpm-lock.yaml", file: "pnpm-lock.yaml", content: PNPM, names: ["zod", "@scope/sdk", "zod-to-json-schema"], expected: ["zod 4.5.4", "@scope/sdk 1.30.0", "zod-to-json-schema 3.24.1"] },
  { format: "yarn.lock classic", file: "yarn.lock", content: YARN_CLASSIC, names: ["zod", "@scope/sdk"], expected: ["zod 3.22.4", "@scope/sdk 1.30.0"] },
  { format: "yarn.lock berry", file: "yarn.lock", content: YARN_BERRY, names: ["zod", "@scope/sdk"], expected: ["zod 4.5.4", "@scope/sdk 1.30.0"] },
  { format: "poetry.lock", file: "poetry.lock", content: POETRY, names: ["Requests", "urllib3"], expected: ["Requests 2.31.0", "urllib3 2.2.1"] },
  { format: "requirements.txt", file: "requirements.txt", content: REQUIREMENTS, names: ["requests", "urllib3"], expected: ["requests 2.31.0", "urllib3 2.2.1"] },
  { format: "Cargo.lock", file: "Cargo.lock", content: CARGO, names: ["serde", "serde_derive"], expected: ["serde 1.0.197", "serde_derive 1.0.197"] },
  { format: "go.sum", file: "go.sum", content: GO_SUM, names: ["github.com/google/uuid", "golang.org/x/sys"], expected: ["github.com/google/uuid v1.6.0", "golang.org/x/sys v0.18.0"] },
  { format: "go.mod", file: "go.mod", content: GO_MOD, names: ["github.com/google/uuid", "golang.org/x/sys"], expected: ["github.com/google/uuid v1.6.0", "golang.org/x/sys v0.18.0"] },
];

// A directory carrying one lockfile and nothing else.
function makeFixture(t, name, file, content) {
  const cwd = makeDir(t, `libs-${name}`);
  writeFileSync(join(cwd, file), content);
  return cwd;
}

// Runs `nightshift libs` in the fixture as a real subprocess.
function runLibs(t, cwd, names) {
  const env = makeHome(t, "libs-caller");
  const result = spawnSync(process.execPath, [CLI, "libs", ...names], { cwd, env, encoding: "utf8" });
  assert.equal(result.error, undefined, `the CLI failed to spawn: ${result.error}`);
  return { code: result.status, lines: result.stdout.split("\n").filter(Boolean), stderr: result.stderr };
}

test("every lockfile format answers with the version installed, never with the range the manifest declares", (t) => {
  for (const fixture of FIXTURES) {
    const cwd = makeFixture(t, fixture.format.replace(/[^a-z0-9]+/gi, "-"), fixture.file, fixture.content);

    const result = runLibs(t, cwd, fixture.names);

    assert.equal(result.code, 0, `${fixture.format}: ${result.stderr}`);
    assert.deepEqual(result.lines, fixture.expected, fixture.format);
  }
});

test("one line comes back per name, in the order the names were given", (t) => {
  const cwd = makeFixture(t, "order", "package-lock.json", NPM_V3);

  const result = runLibs(t, cwd, ["@scope/sdk", "zod", "@scope/sdk"]);

  assert.deepEqual(result.lines, ["@scope/sdk 1.30.0", "zod 4.5.4", "@scope/sdk 1.30.0"]);
  assert.equal(result.code, 0, result.stderr);
});

test("a name the lockfile does not carry prints not-found and does not fail the command", (t) => {
  const cwd = makeFixture(t, "not-found", "package-lock.json", NPM_V3);

  const result = runLibs(t, cwd, ["zod", "react"]);

  assert.deepEqual(result.lines, ["zod 4.5.4", "react not-found"]);
  assert.equal(result.code, 0, result.stderr);
});

test("a directory with no lockfile at all reports every name not-found, says why on stderr and still exits 0", (t) => {
  const cwd = makeDir(t, "libs-no-lockfile");

  const result = runLibs(t, cwd, ["zod", "react"]);

  assert.deepEqual(result.lines, ["zod not-found", "react not-found"]);
  assert.match(result.stderr, /no lockfile in/);
  assert.equal(result.code, 0, result.stderr);
});

test("a corrupt lockfile is refused instead of being reported as not-found", (t) => {
  const cwd = makeFixture(t, "corrupt", "package-lock.json", "{ this is not json");

  const result = runLibs(t, cwd, ["zod"]);

  assert.equal(result.code, 1);
  assert.match(result.stderr, /package-lock\.json is not valid JSON/);
  assert.deepEqual(result.lines, []);
});

test("a call with no name is refused with the usage line", (t) => {
  const cwd = makeFixture(t, "no-name", "package-lock.json", NPM_V3);

  const result = runLibs(t, cwd, []);

  assert.equal(result.code, 1);
  assert.match(result.stderr, /missing argument; usage: nightshift libs <name>\.\.\./);
});
